// rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'god' | 'unique' | null(未分類)
const PREDEFINED_ITEMS = [
    { id: 'i1',   name: '石',                              rarity: 'common'},
    { id: 'i2',   name: '欠けたルビー',                    rarity: 'common' },
    { id: 'i3',   name: '欠けたサファイア',                rarity: 'common' },
    { id: 'i4',   name: '欠けたトパーズ',                  rarity: 'common' },
    { id: 'i5',   name: '欠けたエメラルド',                rarity: 'common' },
    { id: 'i6',   name: '欠けたアメシスト',                rarity: 'common' },
    { id: 'i7',   name: '勇気の星',                        rarity: 'unique' },
    { id: 'i8',   name: 'ニンニク',                        rarity: 'common' },
    { id: 'i9',   name: '石炭のかたまり',                  rarity: 'common' },
    { id: 'i10',  name: 'ひとつかみの砂',                  rarity: 'common' },
    { id: 'i11',  name: '輝く殻',                          rarity: 'common' },
    { id: 'i12',  name: 'チビバート',                      rarity: 'common' },
    { id: 'i13',  name: 'ブルーベリー',                    rarity: 'rare' },
    { id: 'i14',  name: '燃える石炭',                      rarity: 'rare' },
    { id: 'i15',  name: '傷物のルビー',                    rarity: 'rare' },
    { id: 'i16',  name: '傷物のサファイア',                rarity: 'rare' },
    { id: 'i17',  name: '傷物のトパーズ',                  rarity: 'rare' },
    { id: 'i18',  name: '傷物のエメラルド',                rarity: 'rare' },
    { id: 'i19',  name: '傷物のアメシスト',                rarity: 'rare' },
    { id: 'i20',  name: '守護のハンドバッグ',              rarity: 'god' },
    { id: 'i21',  name: '木の剣',                          rarity: 'common' },
    { id: 'i22',  name: 'バナナ',                          rarity: 'common' },
    { id: 'i23',  name: 'ブタちゃん貯金箱',                rarity: 'common' },
    { id: 'i24',  name: '石入り袋',                        rarity: 'rare' },
    { id: 'i25',  name: 'ウエストポーチ',                  rarity: 'rare' },
    { id: 'i26',  name: '未知のスキル',                    rarity: 'unique' },
    { id: 'i27',  name: '癒やしのハーブ',                  rarity: 'common' },
    { id: 'i28',  name: 'フライパン',                      rarity: 'common' },
    { id: 'i29',  name: 'ホウキ',                          rarity: 'common' },
    { id: 'i30',  name: '木の盾',                          rarity: 'common' },
    { id: 'i31',  name: 'セイウチの牙',                    rarity: 'common' },
    { id: 'i32',  name: '砥石',                            rarity: 'common' },
    { id: 'i33',  name: 'ゴーストダガー',                  rarity: 'legendary' },
    { id: 'i34',  name: '革のカバン',                      rarity: 'common' },
    { id: 'i35',  name: 'ダガー',                          rarity: 'rare' },
    { id: 'i36',  name: '迅速のグローブ',                  rarity: 'rare' },
    { id: 'i37',  name: 'ヘルスポーション',                rarity: 'rare' },
    { id: 'i38',  name: 'ショップ会員カード',              rarity: 'rare' },
    { id: 'i39',  name: '雪玉',                            rarity: 'epic' },
    { id: 'i40',  name: '普通のルビー',                    rarity: 'epic' },
    { id: 'i41',  name: '普通のサファイア',                rarity: 'epic' },
    { id: 'i42',  name: '普通のトパーズ',                  rarity: 'epic' },
    { id: 'i43',  name: '普通のエメラルド',                rarity: 'epic' },
    { id: 'i44',  name: '普通のアメシスト',                rarity: 'epic' },
    { id: 'i45',  name: '富の宝箱',                        rarity: 'rare' },
    { id: 'i46',  name: 'たいまつ',                        rarity: 'rare' },
    { id: 'i47',  name: '殻のトーテム',                    rarity: 'rare' },
    { id: 'i48',  name: '燃えるたいまつ',                  rarity: 'epic' },
    { id: 'i49',  name: 'サンドバッグ卿',                  rarity: 'epic' },
    { id: 'i50',  name: 'スタミナバッグ',                  rarity: 'epic' },
    { id: 'i51',  name: '財宝の箱',                        rarity: 'epic' },
    { id: 'i52',  name: 'ポーションベルト',                rarity: 'legendary' },
    { id: 'i53',  name: 'スパイシーバナナ',                rarity: 'unique' },
    { id: 'i54',  name: '臭い立つ防壁',                    rarity: 'unique' },
    { id: 'i55',  name: 'ブタちゃんピニャータ',            rarity: 'unique' },
    { id: 'i56',  name: '投資機会',                        rarity: 'unique' },
    { id: 'i57',  name: '大容量',                          rarity: 'unique' },
    { id: 'i58',  name: 'イッツ・スライムタイム！',        rarity: 'unique' },
    { id: 'i59',  name: 'サルでもわかる鍛冶',              rarity: 'unique' },
    { id: 'i60',  name: 'ちょっと力を！',                  rarity: 'unique' },
    { id: 'i61',  name: 'ユニークなユニーク',              rarity: 'unique' },
    { id: 'i62',  name: '深堀り',                          rarity: 'unique' },
    { id: 'i63',  name: 'ナイフ・トゥ・ミーチュー',        rarity: 'unique' },
    { id: 'i64',  name: '庇護',                            rarity: 'unique' },
    { id: 'i65',  name: '石塁',                            rarity: 'unique' },
    { id: 'i66',  name: '魔法熟達',                        rarity: 'unique' },
    { id: 'i67',  name: '月の力',                          rarity: 'unique' },
    { id: 'i68',  name: 'ガブ飲み',                        rarity: 'unique' },
    { id: 'i69',  name: 'ガールパワー',                    rarity: 'unique' },
    { id: 'i70',  name: '血操術',                          rarity: 'unique' },
    { id: 'i71',  name: '爆ぜる荊棘',                      rarity: 'unique' },
    { id: 'i72',  name: 'こだまする雄叫び',                rarity: 'unique' },
    { id: 'i73',  name: '武器エンチャント',                rarity: 'unique' },
    { id: 'i74',  name: '急かさないで！',                  rarity: 'unique' },
    { id: 'i75',  name: 'ダブルレインボー',                rarity: 'unique' },
    { id: 'i76',  name: '偽りの命',                        rarity: 'unique' },
    { id: 'i77',  name: 'フォルトゥナのキス',              rarity: 'unique' },
    { id: 'i78',  name: '堅木',                            rarity: 'unique' },
    { id: 'i79',  name: '神の光も金次第',                  rarity: 'unique' },
    { id: 'i80',  name: 'バッグり仰天',                    rarity: 'unique' },
    { id: 'i81',  name: 'もっと力を！',                    rarity: 'unique' },
    { id: 'i82',  name: '時間融解',                        rarity: 'unique' },
    { id: 'i83',  name: '全身防備',                        rarity: 'unique' },
    { id: 'i84',  name: 'リーフバッジ',                    rarity: 'unique' },
    { id: 'i85',  name: 'スカルバッジ',                    rarity: 'unique' },
    { id: 'i86',  name: 'ウルフバッジ',                    rarity: 'unique' },
    { id: 'i87',  name: 'フレイムバッジ',                  rarity: 'unique' },
    { id: 'i88',  name: 'レインボーバッジ',                rarity: 'unique' },
    { id: 'i89',  name: 'ストーンバッジ',                  rarity: 'unique' },
    { id: 'i90',  name: 'マジックバッジ',                  rarity: 'unique' },
    { id: 'i91',  name: 'パズルバッジ',                    rarity: 'unique' },
    { id: 'i92',  name: '結び糸バッジ',                    rarity: 'unique' },
    { id: 'i93',  name: 'スピア',                          rarity: 'rare' },
    { id: 'i94',  name: '未鑑定のアミュレット',            rarity: 'rare' },
    { id: 'i95',  name: '生命のアミュレット',              rarity: 'rare' },
    { id: 'i96',  name: '鋼鉄のアミュレット',              rarity: 'rare' },
    { id: 'i97',  name: '大食のアミュレット',              rarity: 'rare' },
    { id: 'i98',  name: '暗黒のアミュレット',              rarity: 'rare' },
    { id: 'i99',  name: '活力のアミュレット',              rarity: 'rare' },
    { id: 'i100', name: '野生のアミュレット',              rarity: 'rare' },
    { id: 'i101', name: '秘術のアミュレット',              rarity: 'rare' },
    { id: 'i102', name: '幸福のアミュレット',              rarity: 'rare' },
    { id: 'i103', name: 'スラバート',                      rarity: 'rare' },
    { id: 'i104', name: 'シェリー',                        rarity: 'rare' },
    { id: 'i105', name: '革のブーツ',                      rarity: 'rare' },
    { id: 'i106', name: '硬肌のポーション',                rarity: 'epic' },
    { id: 'i107', name: 'フルート',                        rarity: 'epic' },
    { id: 'i108', name: 'マナオーブ',                      rarity: 'epic' },
    { id: 'i109', name: '不安定な再構築器',                rarity: 'epic' },
    { id: 'i110', name: 'マナポーション',                  rarity: 'epic' },
    { id: 'i111', name: 'ヒーローポーション',              rarity: 'legendary' },
    { id: 'i112', name: 'パイナップル',                    rarity: 'legendary' },
    { id: 'i113', name: '幸運泥棒のアリスイ',              rarity: 'legendary' },
    { id: 'i114', name: 'ポポ',                            rarity: 'unique' },
    { id: 'i115', name: 'スノーケーキ',                    rarity: 'unique' },
    { id: 'i116', name: '安定した再構築器',                rarity: 'unique' },
    { id: 'i117', name: 'チェストナット君',                rarity: 'unique' },
    { id: 'i118', name: '革の鎧',                          rarity: 'rare' },
    { id: 'i119', name: '飢えたる剣',                      rarity: 'epic' },
    { id: 'i120', name: '疫毒のフラスコ',                  rarity: 'epic' },
    { id: 'i121', name: '不屈のヘルム',                    rarity: 'epic' },
    { id: 'i122', name: '堕落のクリスタル',                rarity: 'epic' },
    { id: 'i123', name: 'オイルランプ',                    rarity: 'epic' },
    { id: 'i124', name: '英雄の剣',                        rarity: 'epic' },
    { id: 'i125', name: '旅行カバン',                      rarity: 'epic' },
    { id: 'i126', name: '聖なるポーション',                rarity: 'legendary' },
    { id: 'i127', name: 'ラッパ',                          rarity: 'god' },
    { id: 'i128', name: 'ハッピーボム',                    rarity: 'unique' },
    { id: 'i129', name: '血の大鎌',                        rarity: 'unique' },
    { id: 'i130', name: '悪党の剣',                        rarity: 'unique' },
    { id: 'i131', name: '吸血のポーション',                rarity: 'legendary' },
    { id: 'i132', name: 'ハンマー',                        rarity: 'rare' },
    { id: 'i133', name: '時間膨張時計',                    rarity: 'unique' },
    { id: 'i134', name: 'シャベル',                        rarity: 'rare' },
    { id: 'i135', name: 'トゲの盾',                        rarity: 'rare' },
    { id: 'i136', name: 'パンプキン',                      rarity: 'unique' },
    { id: 'i137', name: '羊飼いの杖',                      rarity: 'rare' },
    { id: 'i138', name: 'キューバート',                    rarity: 'unique' },
    { id: 'i139', name: 'イバラのムチ',                    rarity: 'epic' },
    { id: 'i140', name: '無傷のルビー',                    rarity: 'legendary' },
    { id: 'i141', name: '無傷のサファイア',                rarity: 'legendary' },
    { id: 'i142', name: '無傷のトパーズ',                  rarity: 'legendary' },
    { id: 'i143', name: '無傷のエメラルド',                rarity: 'legendary' },
    { id: 'i144', name: '無傷のアメシスト',                rarity: 'legendary' },
    { id: 'i145', name: 'グラグラ雪ダルマ',                rarity: 'epic' },
    { id: 'i146', name: 'アタッククロー',                  rarity: 'epic' },
    { id: 'i147', name: 'ハイヘルスポーション',            rarity: 'epic' },
    { id: 'i148', name: 'クトゥルフ',                      rarity: 'unique' },
    { id: 'i149', name: 'プラチナ会員カード',              rarity: 'epic' },
    { id: 'i150', name: '古代の石：デス',                  rarity: 'unique' },
    { id: 'i151', name: '反復機',                          rarity: 'unique' },
    { id: 'i152', name: '凍てつく盾',                      rarity: 'epic' },
    { id: 'i153', name: '血のアミュレット',                rarity: 'legendary' },
    { id: 'i154', name: 'ジンジャーブレッド・ジェリー',    rarity: 'unique' },
    { id: 'i155', name: '雪の棒',                          rarity: 'legendary' },
    { id: 'i156', name: '極硬肌のポーション',              rarity: 'legendary' },
    { id: 'i157', name: 'コインの山',                      rarity: 'rare' },
    { id: 'i158', name: 'ノコ刃の剣',                      rarity: 'legendary' },
    { id: 'i159', name: 'ハイヒーローポーション',          rarity: 'legendary' },
    { id: 'i160', name: '古代の石：フレイム',              rarity: 'unique' },
    { id: 'i161', name: 'ダンシングドラゴン',              rarity: 'unique' },
    { id: 'i162', name: '魔法の杖',                        rarity: 'legendary' },
    { id: 'i163', name: 'ルビーエッグ',                    rarity: 'legendary' },
    { id: 'i164', name: '招きネコ',                        rarity: 'legendary' },
    { id: 'i165', name: '古代の石：フリーズ',              rarity: 'unique'},
    { id: 'i166', name: 'エッグスカリバー',                rarity: 'legendary' },
    { id: 'i167', name: '剛力のグローブ',                  rarity: 'legendary' },
    { id: 'i168', name: 'ライトセイバー',                  rarity: 'god' },
    { id: 'i169', name: 'ルビーの幼竜',                    rarity: 'god' },
    { id: 'i170', name: 'ティム',                          rarity: 'unique' },
    { id: 'i171', name: '不気味な存在',                    rarity: 'unique' },
    { id: 'i172', name: 'プレゼント',                      rarity: 'unique' },
    { id: 'i173', name: 'びっくりサック',                  rarity: 'unique' },
    { id: 'i174', name: 'ポイズンダガー',                  rarity: 'epic' },
    { id: 'i175', name: '氷の鎧',                          rarity: 'epic' },
    { id: 'i176', name: 'パンダモニウム',                  rarity: 'legendary' },
    { id: 'i177', name: '魔法のたいまつ',                  rarity: 'legendary' },
    { id: 'i178', name: 'フロストバイト',                  rarity: 'legendary' },
    { id: 'i179', name: '魔神のランプ',                    rarity: 'god' },
    { id: 'i180', name: '勇気の盾',                        rarity: 'legendary' },
    { id: 'i181', name: '聖なる鎧',                        rarity: 'legendary' },
    { id: 'i182', name: 'ブラッディダガー',                rarity: 'legendary' },
    { id: 'i183', name: '石のブーツ',                      rarity: 'legendary' },
    { id: 'i184', name: '優美なるレイピア',                rarity: 'god' },
    { id: 'i185', name: '輝ける王冠',                      rarity: 'god' },
    { id: 'i186', name: 'ヴォルパーティンガー',            rarity: 'god' },
    { id: 'i187', name: 'ハートの容器',                    rarity: 'god' },
    { id: 'i188', name: '吸血のグローブ',                  rarity: 'god' },
    { id: 'i189', name: 'マナ喰らいの剣',                  rarity: 'legendary' },
    { id: 'i190', name: 'ポイズンスピア',                  rarity: 'legendary' },
    { id: 'i191', name: '石の鎧',                          rarity: 'legendary' },
    { id: 'i192', name: 'スチール・スラバート',            rarity: 'legendary' },
    { id: 'i193', name: '石のヘルム',                      rarity: 'legendary' },
    { id: 'i194', name: 'カタナ',                          rarity: 'god' },
    { id: 'i195', name: 'ウイングブーツ',                  rarity: 'god' },
    { id: 'i196', name: 'ブラッディ・スラバート',          rarity: 'legendary' },
    { id: 'i197', name: '苦痛のヘルム',                    rarity: 'legendary' },
    { id: 'i198', name: 'あまりにも大きすぎるグレートソード', rarity: 'god' },
    { id: 'i199', name: 'プリズムオーブ',                  rarity: 'god' },
    { id: 'i200', name: 'ローズウィップ',                  rarity: 'god' },
    { id: 'i201', name: '英雄のロングソード',              rarity: 'legendary' },
    { id: 'i202', name: 'ハヤブサのつるぎ',                rarity: 'legendary' },
    { id: 'i203', name: '吸血鬼の鎧',                      rarity: 'legendary' },
    { id: 'i204', name: 'ブラッドソーン',                  rarity: 'god' },
    { id: 'i205', name: 'ストーンゴーレム',                rarity: 'god' },
    { id: 'i206', name: 'ライト・スラバート',              rarity: 'god' },
    { id: 'i207', name: '完璧なルビー',                    rarity: 'god' },
    { id: 'i208', name: '完璧なサファイア',                rarity: 'god' },
    { id: 'i209', name: '完璧なトパーズ',                  rarity: 'god' },
    { id: 'i210', name: '完璧なエメラルド',                rarity: 'god' },
    { id: 'i211', name: '完璧なアメシスト',                rarity: 'god' },
    { id: 'i212', name: '毒蛇の杖',                        rarity: 'legendary' },
    { id: 'i213', name: 'ダークセイバー',                  rarity: 'god' },
    { id: 'i214', name: 'プリズムソード',                  rarity: 'god' },
    { id: 'i215', name: '王の冠',                          rarity: 'god' },
    { id: 'i216', name: 'ホーリースピア',                  rarity: 'god' },
    { id: 'i217', name: '月の盾',                          rarity: 'god' },
    { id: 'i218', name: '月の鎧',                          rarity: 'god' },
    { id: 'i219', name: '堕落せし鎧',                      rarity: 'god' },
    { id: 'i220', name: '暗黒のハート',                    rarity: 'god' },
    { id: 'i221', name: '極楽チュン',                      rarity: 'god' },
    { id: 'i222', name: 'キング・スラバート',              rarity: 'god' },
    { id: 'i223', name: 'クロスブレード',                  rarity: 'god' },
    { id: 'i224', name: 'ショートボウ',                    rarity: 'common' },
    { id: 'i225', name: '突きキバの短弓',                  rarity: 'rare' },
    { id: 'i226', name: '弓矢',                            rarity: 'epic' },
    { id: 'i227', name: 'フォルトゥナの願い弓',            rarity: 'epic' },
    { id: 'i228', name: 'リス・アーチャー',                rarity: 'epic' },
    { id: 'i229', name: 'クリティカルの杖',                rarity: 'legendary' },
    { id: 'i230', name: 'つらぬきキバの弓矢',              rarity: 'legendary' },
    { id: 'i231', name: 'フォルトゥナの加護弓',            rarity: 'legendary' },
    { id: 'i232', name: 'ささやきベラドンナの毒弓',        rarity: 'legendary' },
    { id: 'i233', name: 'ベラドンナの影毒弓',              rarity: 'legendary' },
    { id: 'i234', name: '幸運のクローバー',                rarity: 'rare' },
    { id: 'i235', name: 'ドングリの首飾り',                rarity: 'epic' },
    { id: 'i236', name: '幸運のブタちゃん',                rarity: 'epic' },
    { id: 'i237', name: '赤ランの首飾り',                  rarity: 'legendary' },
    { id: 'i238', name: '青セージの首飾り',                rarity: 'legendary' },
    { id: 'i239', name: '白ユリの首飾り',                  rarity: 'legendary' },
    { id: 'i240', name: 'つらぬきの矢',                    rarity: 'unique' },
    { id: 'i241', name: 'ユグドラシルの葉',                rarity: 'unique' },
    { id: 'i242', name: 'ドクウルシ',                      rarity: 'unique' },
    { id: 'i243', name: 'メガ・クローバー',                rarity: 'unique' },
    { id: 'i244', name: 'レンジャーのカバン',              rarity: 'unique' },
    { id: 'i245', name: 'つる織りバスケット',              rarity: 'unique' },
    { id: 'i246', name: 'ネズミ',                          rarity: 'commin' },
    { id: 'i247', name: 'リス',                            rarity: 'rare' },
    { id: 'i248', name: 'ネズミ・シェフ',                  rarity: 'rare' },
    { id: 'i249', name: 'ハリネズミ',                      rarity: 'epic' },
    { id: 'i250', name: 'ニンジン・スラバート',            rarity: 'epic' },
    { id: 'i251', name: 'スノーマスター',                  rarity: 'legendary' },
    { id: 'i252', name: 'レインボー・スラバート・マッド・アルファ', rarity: 'god' },
    { id: 'i253', name: 'ハイパー・ハリネズミ',            rarity: 'god' },
    { id: 'i254', name: 'ニンジン',                        rarity: 'rare' },
    { id: 'i255', name: 'エサの盛り合わせ',                rarity: 'unique' },
    { id: 'i256', name: 'マークスウーマン',                rarity: 'unique' },
    { id: 'i257', name: 'ドングリ・エース',                rarity: 'unique' },
    { id: 'i258', name: '死神の鎌',                        rarity: 'legendary' },
    { id: 'i259', name: '呪われしダガー',                  rarity: 'unique' },
    { id: 'i260', name: 'ルビーの火トカゲ',                rarity: 'god' },
    { id: 'i261', name: '癒さずの杖',                      rarity: 'god' },
    { id: 'i262', name: 'アイスドラゴン',                  rarity: 'god' },
    { id: 'i263', name: 'カードデッキ',                    rarity: 'rare' },
    { id: 'i264', name: 'ミス・フォーチュン',              rarity: 'epic' },
    { id: 'i265', name: 'ミセス・ストラグルズ',            rarity: 'legendary' },
    { id: 'i266', name: '夜闇のヘアコーム',                rarity: 'god' },
    { id: 'i267', name: 'ミスター・ストラグルズ',          rarity: 'god' },
    { id: 'i268', name: '大ナベ',                          rarity: 'unique' },
    { id: 'i269', name: '棺型バッグ',                      rarity: 'unique' },
    { id: 'i270', name: 'レリックケース',                  rarity: 'unique' },
    { id: 'i271', name: 'カエル',                          rarity: 'epic' },
    { id: 'i272', name: 'ポイズン・スラバート',            rarity: 'epic' },
    { id: 'i273', name: 'ドクガエル',                      rarity: 'legendary' },
    { id: 'i274', name: 'レインボー・スラバート・プライム・オメガ', rarity: 'god' },
    { id: 'i275', name: 'カラス',                          rarity: 'god' },
    { id: 'i276', name: 'ヘビ',                            rarity: 'unique' },
    { id: 'i277', name: '恋人のカード',                    rarity: 'common' },
    { id: 'i278', name: 'スペードのエース',                rarity: 'rare' },
    { id: 'i279', name: 'リバース！',                      rarity: 'rare' },
    { id: 'i280', name: '白眼の青龍',                      rarity: 'epic' },
    { id: 'i281', name: '愚者のカード',                    rarity: 'epic' },
    { id: 'i282', name: '炎トカゲのホロカード',            rarity: 'legendary' },
    { id: 'i283', name: 'ダーク・ロータス',                rarity: 'god' },
    { id: 'i284', name: 'ジョーカー',                      rarity: 'god' },
    { id: 'i285', name: 'デス・ロータス',                  rarity: 'god' },
    { id: 'i286', name: '強疫毒のフラスコ',                rarity: 'legendary' },
    { id: 'i287', name: 'ハイマナポーション',              rarity: 'legendary' },
    { id: 'i288', name: '悪鬼のフラスコ',                  rarity: 'god' },
    { id: 'i289', name: '凶悪鬼のフラスコ',                rarity: 'god' },
    { id: 'i290', name: '極吸血のポーション',              rarity: 'god' },
    { id: 'i291', name: '神聖なるポーション',              rarity: 'god' },
    { id: 'i292', name: 'ベニテングダケ',                  rarity: 'rare' },
    { id: 'i293', name: 'ハメツダケ',                      rarity: 'god' },
    { id: 'i294', name: 'キノコ農園',                      rarity: 'unique' },
    { id: 'i295', name: 'カードの心臓',                    rarity: 'unique' },
    { id: 'i296', name: '闇の儀式',                        rarity: 'unique' },
    { id: 'i297', name: 'フレイム',                        rarity: 'common' },
    { id: 'i298', name: 'トウガラシ',                      rarity: 'rare' },
    { id: 'i299', name: '呪文の巻物：霜撃',                rarity: 'rare' },
    { id: 'i300', name: 'ドラゴンオーブ',                  rarity: 'epic' },
    { id: 'i301', name: 'ヒートダガー',                    rarity: 'epic' },
    { id: 'i302', name: 'ヒートスピア',                    rarity: 'epic' },
    { id: 'i303', name: '炎の剣',                          rarity: 'epic' },
    { id: 'i304', name: 'トウガラシ・スラバート',          rarity: 'epic' },
    { id: 'i305', name: 'ターボ・シェリー',                rarity: 'epic' },
    { id: 'i306', name: 'フェニックス',                    rarity: 'legendary' },
    { id: 'i307', name: 'エメラルドエッグ',                rarity: 'legendary' },
    { id: 'i308', name: 'サファイアエッグ',                rarity: 'legendary' },
    { id: 'i309', name: 'アメシストエッグ',                rarity: 'legendary' },
    { id: 'i310', name: '灼炎の剣',                        rarity: 'legendary' },
    { id: 'i311', name: 'フレイムウィップ',                rarity: 'legendary' },
    { id: 'i312', name: '炎の杖',                          rarity: 'legendary' },
    { id: 'i313', name: 'エメラルドの幼竜',                rarity: 'god' },
    { id: 'i314', name: 'サファイアの幼竜',                rarity: 'god' },
    { id: 'i315', name: 'アメシストの幼竜',                rarity: 'god' },
    { id: 'i316', name: 'ヒートグレートソード',            rarity: 'god' },
    { id: 'i317', name: '黒曜のドラゴン',                  rarity: 'god' },
    { id: 'i318', name: '太陽の盾',                        rarity: 'god' },
    { id: 'i319', name: '太陽の鎧',                        rarity: 'god' },
    { id: 'i320', name: 'レインボー・スラバート・エピック・ウーバー', rarity: 'god' },
    { id: 'i321', name: '常炎',                            rarity: 'unique' },
    { id: 'i322', name: 'ソラリス',                        rarity: 'unique' },
    { id: 'i323', name: 'フレンドリーな火',                rarity: 'unique' },
    { id: 'i324', name: '燃えさかる旗印',                  rarity: 'unique' },
    { id: 'i325', name: '闇のランタン',                    rarity: 'unique' },
    { id: 'i326', name: 'フローズンフレイム',              rarity: 'unique' },
    { id: 'i327', name: 'ドラゴンの寝床',                  rarity: 'unique' },
    { id: 'i328', name: 'たき火台',                        rarity: 'unique' },
    { id: 'i329', name: '供物皿',                          rarity: 'unique' },
    { id: 'i330', name: 'オノ',                            rarity: 'rare' },
    { id: 'i331', name: 'ダブルアックス',                  rarity: 'legendary' },
    { id: 'i332', name: '勇敢な子狼',                      rarity: 'legendary' },
    { id: 'i333', name: 'チェーンウィップ',                rarity: 'legendary' },
    { id: 'i334', name: 'トゲの杖',                        rarity: 'legendary' },
    { id: 'i335', name: '破滅のグレートソード',            rarity: 'god' },
    { id: 'i336', name: '武装した勇敢な子狼',              rarity: 'god' },
    { id: 'i337', name: '鍛冶屋のハンマー',                rarity: 'unique' },
    { id: 'i338', name: 'ブラスナックル',                  rarity: 'unique' },
    { id: 'i339', name: 'トゲつきチョーカー',              rarity: 'legendary' },
    { id: 'i340', name: '狼の紋章',                        rarity: 'unique' },
    { id: 'i341', name: 'かなとこ',                        rarity: 'unique' },
    { id: 'i342', name: 'シカ神のトーテム',                rarity: 'unique' },
    { id: 'i343', name: 'シャーマンの仮面',                rarity: 'unique' },
    { id: 'i344', name: 'ダッフルバッグ',                  rarity: 'unique' },
    { id: 'i345', name: '便利ポーチ',                      rarity: 'unique' },
    { id: 'i346', name: 'アナグマのルーン',                rarity: 'legendary' },
    { id: 'i347', name: 'ゾウのルーン',                    rarity: 'legendary' },
    { id: 'i348', name: 'タカのルーン',                    rarity: 'legendary' },
    { id: 'i349', name: 'トラのルーン',                    rarity: 'legendary' },
    { id: 'i350', name: '聡明な子狼',                      rarity: 'legendary' },
    { id: 'i351', name: '力持ちの子狼',                    rarity: 'legendary' },
    { id: 'i352', name: 'チーズ・スラバート',              rarity: 'god' },
    { id: 'i353', name: 'レインボー・スラバート・デス・マンイーター', rarity: 'god' },
    { id: 'i354', name: '武装した聡明な子狼',              rarity: 'god' },
    { id: 'i355', name: '武装した力持ちの子狼',            rarity: 'god' },
    { id: 'i356', name: 'チーズ',                          rarity: 'legendary' },
    { id: 'i357', name: 'トゲの壁',                        rarity: 'god' },
    { id: 'i358', name: '竜鱗の鎧',                        rarity: 'epic' },
    { id: 'i359', name: 'ドラゴン革のブーツ',              rarity: 'epic' },
    { id: 'i360', name: 'ドラゴンクロー',                  rarity: 'epic' },
    { id: 'i361', name: 'さらなる怒り',                    rarity: 'unique' },
    { id: 'i362', name: 'ドラゴンセット',                  rarity: 'unique' },
    { id: 'i363', name: '無の剣',                          rarity: 'god' },
    { id: 'i364', name: 'カップケーキの杖',                rarity: 'legendary' },
    { id: 'i365', name: '水のエレメンタル',                rarity: 'unique' },
    { id: 'i366', name: '均衡のワンド',                    rarity: 'common' },
    { id: 'i367', name: 'チェスボード',                    rarity: 'rare' },
    { id: 'i368', name: 'プリズムワンド',                  rarity: 'god' },
    { id: 'i369', name: '精霊のベル',                      rarity: 'unique' },
    { id: 'i370', name: '愛情のパズルバッグ',              rarity: 'common' },
    { id: 'i371', name: '改善のパズルバッグ',              rarity: 'rare' },
    { id: 'i372', name: '破滅のパズルバッグ',              rarity: 'epic' },
    { id: 'i373', name: '活力のパズルバッグ',              rarity: 'legendary'},
    { id: 'i374', name: '持続のパズルバッグ',              rarity: 'god'},
    { id: 'i375', name: '学者のカバン',                    rarity: 'unique' },
    { id: 'i376', name: 'パズルボックス',                  rarity: 'unique' },
    { id: 'i377', name: 'ネコの精霊',                      rarity: 'legendary' },
    { id: 'i378', name: 'フクロウの精霊',                  rarity: 'legendary' },
    { id: 'i379', name: 'アナグマの精霊',                  rarity: 'legendary' },
    { id: 'i380', name: 'カップケーキ・スラバート',        rarity: 'legendary' },
    { id: 'i381', name: 'レインボー・スラバート・オムニ・シュガー', rarity: 'god' },
    { id: 'i382', name: '憎たらしい帽子・ハロルド',        rarity: 'unique'},
    { id: 'i383', name: 'ゼロから学ぶ魔法',                rarity: 'common' },
    { id: 'i384', name: '氷結魔法の手引き',                rarity: 'rare' },
    { id: 'i385', name: '自然の年代記：木々',              rarity: 'epic'},
    { id: 'i386', name: '暗黒の百科事典',                  rarity: 'legendary'},
    { id: 'i387', name: '神聖なる経典',                    rarity: 'god'},
    { id: 'i388', name: '呪文の巻物：再生',                rarity: 'rare'},
    { id: 'i389', name: '呪文の巻物：清らかなる祝福',      rarity: 'epic' },
    { id: 'i390', name: '呪文の巻物：氷の障壁',            rarity: 'legendary'},
    { id: 'i391', name: 'ランタンベリー',                  rarity: 'legendary'},
    { id: 'i392', name: 'コールドミラー',                  rarity: 'god'},
    { id: 'i393', name: 'アイスフラワー',                  rarity: 'god'},
    { id: 'i394', name: '貪食のスフィア',                  rarity: 'god'},
    { id: 'i396', name: '呪文の巻物：闇の狂乱',            rarity: 'god'},
    { id: 'i397', name: '白のポーン',                      rarity: 'common' },
    { id: 'i398', name: '黒のポーン',                      rarity: 'common' },
    { id: 'i399', name: '白のナイト',                      rarity: 'rare' },
    { id: 'i400', name: '黒のナイト',                      rarity: 'rare' },
    { id: 'i401', name: '白のビショップ',                  rarity: 'rare' },
    { id: 'i402', name: '黒のビショップ',                  rarity: 'rare' },
    { id: 'i403', name: '白のルーク',                      rarity: 'epic' },
    { id: 'i404', name: '黒のルーク',                      rarity: 'epic' },
    { id: 'i405', name: '白のクイーン',                    rarity: 'legendary' },
    { id: 'i406', name: '黒のクイーン',                    rarity: 'legendary' },
    { id: 'i407', name: '白のキング',                      rarity: 'god' },
    { id: 'i408', name: '黒のキング',                      rarity: 'god' },
    { id: 'i409', name: 'レインボーポーション',            rarity: 'unique' },
    { id: 'i410', name: 'カップケーキ',                    rarity: 'legendary' },
    { id: 'i411', name: '輝く外套',                        rarity: 'unique' },
    { id: 'i412', name: 'メイジの帽子',                    rarity: 'epic'},
    { id: 'i413', name: '魔眼',                            rarity: 'unique' },
    { id: 'i414', name: '超覚醒',                          rarity: 'unique' },
    { id: 'i415', name: '結び糸',                          rarity: 'common' },
    { id: 'i416', name: 'ブロッコリー',                    rarity: 'rare'},
    { id: 'i417', name: 'レベルアップ',                    rarity: 'unique'},
    { id: 'i418', name: 'ブーメラン',                      rarity: 'rare'},
    { id: 'i419', name: '英雄の盾',                        rarity: 'rare'},
    { id: 'i420', name: 'ロープ',                          rarity: 'rare'},
    { id: 'i421', name: '宝箱',                            rarity: 'epic'},
    { id: 'i422', name: 'ベリーロングスピア',              rarity: 'epic'},
    { id: 'i423', name: '二刀流',                          rarity: 'unique' },
    { id: 'i424', name: 'ダガーラン',                      rarity: 'epic'},
    { id: 'i425', name: '従業員の制服',                    rarity: 'epic'},
    { id: 'i426', name: 'ブロッコリー・スラバート',        rarity: 'epic'},
    { id: 'i427', name: '富のブタちゃん',                  rarity: 'epic'},
    { id: 'i428', name: 'アリスイの杖',                    rarity: 'god' },
    { id: 'i429', name: 'ドラゴンナイト',                  rarity: 'god' },
    { id: 'i430', name: 'ハートの盾',                      rarity: 'god' },
    { id: 'i431', name: 'レインボー・スラバート・ギガ・ロマネスコ', rarity: 'god' },
    { id: 'i432', name: 'あまりにも大きすぎるブラッドソーン', rarity: 'god' },
    { id: 'i433', name: '水銀のエレメンタル',              rarity: 'unique' },
    { id: 'i434', name: 'フェドーラ帽',                    rarity: 'unique' },
    { id: 'i435', name: 'カメ',                            rarity: 'unique' },
    { id: 'i436', name: 'シザーソード',                    rarity: 'god' },
    { id: 'i437', name: '天秤',                            rarity: 'unique' },
    { id: 'i438', name: '裁縫セット',                      rarity: 'unique' },
    { id: 'i439', name: 'ウクレレ',                        rarity: 'unique' },
    { id: 'i440', name: '施し袋',                          rarity: 'unique' },
    { id: 'i441', name: 'バッテリー',                      rarity: 'common' },
    { id: 'i442', name: '光輝のアミュレット',              rarity: 'rare' },
    { id: 'i443', name: '煮え立つ鍋',                      rarity: 'rare' },
    { id: 'i444', name: '仕上砥石',                        rarity: 'rare'},
    { id: 'i445', name: '食パン',                          rarity: 'rare'},
    { id: 'i446', name: 'トースト',                        rarity: 'epic'},
    { id: 'i447', name: '歯車',                            rarity: 'rare'},
    { id: 'i448', name: 'マナナ',                          rarity: 'rare'},
    { id: 'i449', name: '鋼の核',                          rarity: 'epic'},
    { id: 'i450', name: '発電機',                          rarity: 'rare' },
    { id: 'i451', name: 'コイル',                          rarity: 'epic'},
    { id: 'i452', name: '分電器',                          rarity: 'epic'},
    { id: 'i453', name: 'レンチ',                          rarity: 'epic'},
    { id: 'i454', name: 'トールハンマー',                  rarity: 'epic'},
    { id: 'i456', name: '電動たいまつ',                    rarity: 'epic' },
    { id: 'i457', name: 'スタンクスの爪楊枝',              rarity: 'legendary' },
    { id: 'i458', name: 'ハルバード',                      rarity: 'legendary'},
    { id: 'i459', name: 'ブレイズスピア',                  rarity: 'legendary'},
    { id: 'i460', name: '魔法の指輪',                      rarity: 'legendary'},
    { id: 'i461', name: 'チェーンソー',                    rarity: 'legendary'},
    { id: 'i462', name: '雷の杖',                          rarity: 'legendary' },
    { id: 'i463', name: 'メカバット',                      rarity: 'legendary' },
    { id: 'i464', name: '才気のヘルム',                    rarity: 'legendary' },
    { id: 'i465', name: '神秘のブーツ',                    rarity: 'legendary' },
    { id: 'i466', name: 'ポイズングレネード',              rarity: 'legendary' },
    { id: 'i467', name: 'トースト・スラバート',            rarity: 'legendary' },
    { id: 'i468', name: 'ウィスプ',                        rarity: 'god'},
    { id: 'i469', name: 'シャベルB01-3000',                rarity: 'legendary' },
    { id: 'i470', name: 'バネ式加速器',                    rarity: 'legendary' },
    { id: 'i471', name: '至極の指輪',                      rarity: 'god'},
    { id: 'i472', name: 'パインの盾',                      rarity: 'god'},
    { id: 'i473', name: '不協和のワンド',                  rarity: 'god'},
    { id: 'i474', name: '動物との対話',                    rarity: 'unique' },
    { id: 'i475', name: '交渉成立',                        rarity: 'unique' },
    { id: 'i476', name: 'キンキラ・キング',                rarity: 'unique' },
    { id: 'i477', name: '金の鎧',                          rarity: 'god' },
    { id: 'i478', name: 'カエル王子',                      rarity: 'god' },
    { id: 'i479', name: 'フォレストドラゴン',              rarity: 'god' },
    { id: 'i480', name: 'パンツァードラゴン',              rarity: 'god' },
    { id: 'i481', name: '致死毒',                          rarity: 'unique' },
    { id: 'i482', name: '戦鎌',                            rarity: 'god'},
    { id: 'i483', name: 'カップドレイク',                  rarity: 'god'},
    { id: 'i484', name: '内なる力',                        rarity: 'unique' },
    { id: 'i485', name: '怒れるフェニックス',              rarity: 'god'},
    { id: 'i486', name: '灼熱の棘',                        rarity: 'unique' },
    { id: 'i487', name: 'チェスマスター',                  rarity: 'unique' },
    { id: 'i488', name: '呪術',                            rarity: 'unique' },
    { id: 'i489', name: 'ブロッコツリー',                  rarity: 'god'},
    { id: 'i490', name: 'アブラガダブラ',                  rarity: 'unique' },
    { id: 'i491', name: 'オートマナトン',                  rarity: 'god' },
    { id: 'i492', name: 'サンダードレイク',                rarity: 'god' },
    { id: 'i493', name: 'ギガワット',                      rarity: 'unique' },
    { id: 'i494', name: 'エネルギー変換',                  rarity: 'unique' },
    { id: 'i495', name: 'ブッパナシネーター',              rarity: 'god'},
    { id: 'i496', name: 'ルーレット',                      rarity: 'unique' },
    { id: 'i497', name: '魔導の鎧',                        rarity: 'god'},
    { id: 'i498', name: 'レインボー・スラバート・フラッフィー・プリズム', rarity: 'god'},
    { id: 'i499', name: 'コン・トラップ・トロン',          rarity: 'god' },
    { id: 'i500', name: 'イート・オ・マティック',          rarity: 'god' },
    { id: 'i501', name: '永久運動',                        rarity: 'unique' },
    { id: 'i502', name: 'トゲのエレメンタル',              rarity: 'unique' },
    { id: 'i503', name: '瓶詰の雷',                        rarity: 'unique' },
    { id: 'i504', name: 'サブスク高級プラン',              rarity: 'unique' },
    { id: 'i505', name: '天使のクリスタル',                rarity: 'unique' },
    { id: 'i506', name: 'ナマケモノ',                      rarity: 'unique' },
    { id: 'i507', name: '歯車バッジ',                      rarity: 'unique' },
    { id: 'i508', name: 'テスラコイル',                    rarity: 'unique' },
    { id: 'i509', name: 'マナクリスタル',                  rarity: 'unique' },
    { id: 'i510', name: '実験所',                          rarity: 'unique' },
    { id: 'i511', name: 'メカアーマー',                    rarity: 'unique' },
    { id: 'i512', name: 'ハイパーキューブ',                rarity: 'unique' },
    { id: 'i513', name: 'ゴールドキューブ',                rarity: 'unique' },
    { id: 'i514', name: 'ビスマスキューブ',                rarity: 'unique' },
    { id: 'i515', name: 'クロムキューブ',                  rarity: 'unique' },
    { id: 'i516', name: 'プラスチックキューブ',            rarity: 'unique' },
    { id: 'i517', name: 'ポート・オ・チャージャー',        rarity: 'unique' },
    { id: 'i518', name: '歯車仕掛けの箱',                  rarity: 'unique' },
];
